### ISSUE TITLE
Revamp website

### ISSUE THREAD

**Issue by LadyBluenotes** [Global-Chem/global-chem-website#1]
As per convo on April 1st (@Sulstice), website needs to be redone. This issue is to start explaining things related to it.

**Hero Section:** An interactive globe is a great idea to show the connections of everyone involved in the project. This could be implemented using a JavaScript library such as Three.js or D3.js. The globe could be displayed in the background of the hero section and allow users to interact with it by hovering over the different nodes to learn more about the people involved in the project.

**Accessibility:** One important consideration is ensuring that the website meets the Web Content Accessibility Guidelines (WCAG) 2.1 AA level standards. This means ensuring that the website is perceivable, operable, understandable, and robust for users with disabilities.

Some ways to consider making it inaccessible:
1. Use clear and simple language for all content.
2. Provide alternate text descriptions for all images and other non-text content.
3. Use high contrast colours to ensure text is easy to read.
4. Ensure all interactive elements are easily accessible via keyboard navigation.
5. Proper HTML structure to ensure that content is properly organized and presented in a logical order.

A lot of the content on the site currently is good, just making sure it better aligns with Global Chem's goals would be a better direction.

**Comment by Sulstice** [comment]
Hey @LadyBluenotes,

For the website. I liked the globe wrapper we had around threejs: https://globe.gl/. I think this would be very cool to implement. 

As for the section layout:

- First Section: Global background with the connections in place. A navbar at the top and two main buttons. The software and join the community. 
- Second Section: Mission statement (which we have the content for) and a call to action. 
- Third Section - maybe there is a way to track Github stats or something on there to show our community growth. Some metrics. 
- Fourth Section: Who is in our community
- Fifth Section: Open Source Positions. 
- Six Section: A contact form. 
- Seventh Section: Footer. 

What do you think?
