### ISSUE TITLE
SS-7: The thank you message for the website needs to be more aesthetically pleasing. 

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem-website#15]
Currently, when I submit a form through our website. The feedback isn't as clean:

<img width="1440" alt="Screenshot 2023-06-03 at 1 54 00 PM" src="https://github.com/Global-Chem/global-chem-website/assets/11812946/3a3098f3-4f14-459e-8ef9-dfba5c76f17e">

It would be nicer to have  the Thank you centered and maybe a little more cleaner 

![image](https://github.com/Global-Chem/global-chem-website/assets/11812946/2a5b66a0-fe4d-471e-ba5e-30b7094c3514)

Something Like this I think.

**Comment by LadyBluenotes** [comment]
Closing this issue since it's repeated from housekeeping tasks.
