### ISSUE TITLE
SS-1: Thank you message should be a little more cleaner. 

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem-website#8]
<img width="1440" alt="Screenshot 2023-05-25 at 7 03 30 AM" src="https://github.com/Global-Chem/global-chem-website/assets/11812946/5a8df283-1b76-47fa-8787-c78b2458e94a">

It looks like on the PR: https://github.com/Global-Chem/global-chem-website/pull/6

The "Thank you message" should be updated to be a little more cleaner.

**Comment by MarvinCorro** [comment]
This one is probs a good first issue. Also depending on how you want to do style maybe thank you/complete/error messages should appear as toast

**Comment by LadyBluenotes** [comment]
Closing this issue since it's repeated.
